excerpt_separator: ""
pygments: false
markdown: kramdown
url: http://mathewmerrick.github.io
highlighter: rouge
title: Mathew Merrick
tagline: Just Things
description: More Things
paginate: 5
